import React from 'react';

export const metadata = {
  title: 'AI Automated Web System',
  description: 'Generated by Gemini Loop',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  );
}
